### ISSUE TITLE
python 3.5.2 64bit运行例程出错

### ISSUE THREAD

**Issue by beyondyouth** [bopo/pyalgotrade_tushare#5]
Traceback (most recent call last):
  File "/home/book/Workspace/pyal/download.py", line 59, in <module>
    feeds = tools.build_feed(instruments, 2013, 2018, "histdata")
  File "/home/book/.local/lib/python3.5/site-packages/pyalgotrade_tushare/tools.py", line 90, in build_feed
    if not os.path.exists(fileName):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath

**Comment by bopo** [comment]
这个项目，没做兼容性测试，之后我会做下

**Comment by bopo** [comment]
请按照低版本 tushare
